from .main_routes import main_bp
from .auth_routes import auth_bp
from .student_routes import student_bp
from .finance_routes import finance_bp
from .class_routes import class_bp
from .yogatherapia_routes import yogatherapia_bp
from .settings_routes import settings_bp
from .user_routes import user_routes_bp
from .student_portal_routes import student_portal_bp
from .setup_routes import setup_bp
from .bug_report_routes import bug_report_bp
