"""bonos de clases

Revision ID: 516c00fd1a20
Revises: 02f7f996269a
Create Date: 2026-07-21 11:52:21.560911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516c00fd1a20'
down_revision = '02f7f996269a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('clases_totales', sa.Integer(), nullable=False),
    sa.Column('clases_consumidas', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bono_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_asistencia_bono_id', 'bono', ['bono_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asistencia_bono_id', type_='foreignkey')
        batch_op.drop_column('bono_id')

    op.drop_table('bono')
    # ### end Alembic commands ###
