"""baseline esquema tras Fase 0

Revision ID: b3dcf4768ecc
Revises: 
Create Date: 2026-07-20 17:29:35.682559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dcf4768ecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('condiciones_medicas', sa.Text(), nullable=True),
    sa.Column('tipo_cuota', sa.String(length=30), nullable=False),
    sa.Column('matricula_pagada', sa.Boolean(), nullable=True),
    sa.Column('fecha_matricula', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categoria_gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('periodicidad', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('instructor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('configuracion_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('direccion_fiscal', sa.Text(), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('epigrafe_iae', sa.String(length=10), nullable=True),
    sa.Column('regimen_iva', sa.String(length=50), nullable=True),
    sa.Column('tipo_retencion_default', sa.Float(), nullable=True),
    sa.Column('exento_iva', sa.Boolean(), nullable=True),
    sa.Column('texto_exencion_iva', sa.Text(), nullable=True),
    sa.Column('logo_factura', sa.String(length=200), nullable=True),
    sa.Column('pie_factura', sa.Text(), nullable=True),
    sa.Column('serie_factura_default', sa.String(length=10), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_mensual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('especialidad', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cif_nif', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contacto_principal', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sutra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('sanscrito', sa.Text(), nullable=False),
    sa.Column('transliteracion', sa.Text(), nullable=False),
    sa.Column('traduccion', sa.Text(), nullable=False),
    sa.Column('libro', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('frecuencia', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nif_cif', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif_cif')
    )
    op.create_table('evento_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('instructor', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('nombre_proveedor', sa.String(length=100), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('importe_sin_iva', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('archivo_factura', sa.String(length=200), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_gasto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_fijo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('frecuencia', sa.String(length=20), nullable=True),
    sa.Column('dia_cargo', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_gasto.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('instructor', sa.String(length=50), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('fecha_clase', sa.Date(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo_pago', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesion_yogaterapia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('fecha_sesion', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('tipo_sesion', sa.String(length=50), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('objetivos_terapeuticos', sa.Text(), nullable=True),
    sa.Column('tecnicas_aplicadas', sa.Text(), nullable=True),
    sa.Column('posturas_trabajadas', sa.Text(), nullable=True),
    sa.Column('respiracion_pranayama', sa.Text(), nullable=True),
    sa.Column('meditacion_relajacion', sa.Text(), nullable=True),
    sa.Column('estado_inicial', sa.Text(), nullable=True),
    sa.Column('respuesta_sesion', sa.Text(), nullable=True),
    sa.Column('estado_final', sa.Text(), nullable=True),
    sa.Column('observaciones_terapeuta', sa.Text(), nullable=True),
    sa.Column('recomendaciones_casa', sa.Text(), nullable=True),
    sa.Column('proxima_sesion', sa.Text(), nullable=True),
    sa.Column('instructor', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivo_yogaterapia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_yogaterapia_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('tamaño_bytes', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sesion_yogaterapia_id'], ['sesion_yogaterapia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('fecha_clase', sa.Date(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento_calendario.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horario_semanal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura_emitida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('numero_completo', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_prestacion', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('base_imponible', sa.Float(), nullable=False),
    sa.Column('tipo_iva', sa.Float(), nullable=True),
    sa.Column('cuota_iva', sa.Float(), nullable=True),
    sa.Column('tipo_retencion', sa.Float(), nullable=True),
    sa.Column('cuota_retencion', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('exenta_iva', sa.Boolean(), nullable=True),
    sa.Column('motivo_exencion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('archivo_pdf', sa.String(length=200), nullable=True),
    sa.Column('enviada_cliente', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('es_rectificativa', sa.Boolean(), nullable=True),
    sa.Column('factura_origen_id', sa.Integer(), nullable=True),
    sa.Column('motivo_rectificacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['factura_origen_id'], ['factura_emitida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_completo')
    )
    op.create_table('inscripciones_horarios',
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horario_semanal.id'], ),
    sa.PrimaryKeyConstraint('alumno_id', 'horario_id')
    )
    op.create_table('linea_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('tarifa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['factura_emitida.id'], ),
    sa.ForeignKeyConstraint(['tarifa_id'], ['tarifa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linea_factura')
    op.drop_table('inscripciones_horarios')
    op.drop_table('factura_emitida')
    op.drop_table('asistencia')
    op.drop_table('archivo_yogaterapia')
    op.drop_table('sesion_yogaterapia')
    op.drop_table('pago')
    op.drop_table('horario_semanal')
    op.drop_table('gasto_fijo')
    op.drop_table('factura_proveedor')
    op.drop_table('evento_calendario')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('tipo_clase')
    op.drop_table('tarifa')
    op.drop_table('sutra')
    op.drop_table('proveedor')
    op.drop_table('instructor')
    op.drop_table('gasto_mensual')
    op.drop_table('configuracion_fiscal')
    op.drop_table('configuracion')
    op.drop_table('clase')
    op.drop_table('categoria_gasto')
    op.drop_table('alumno')
    # ### end Alembic commands ###
